# Mongo Configuration
mongo:
  name: free5gc
  url: http://mongo

# Mobile Country Code value of HPLMN
mcc: "208"
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: "93"
# Permanent subscription key
key: 8baf473f2f8fd09487cccbd7097c6862
# Operator code (OP or OPC) of the UE
op: 8e27b6af0e692e750f32667a3b14605d

# List all the slices
slices:
  - sst: 01
    sd: 010203
    varqi: 9
    dnn: internet
  - sst: 01
    sd: 112233
    varqi: 9
    dnn: internet2

# All IMSI of UEs
imsi:
  - imsi-208930000000001
  - imsi-208930000000002
  - imsi-208930000000003
