images:
  - name: "amf"
    fulltag: "shynuu/sa-ntn:amf"
    required:
      - "base"

  - name: "smf"
    fulltag: "shynuu/sa-ntn:smf"
    required:
      - "base"

  - name: "ausf"
    fulltag: "shynuu/sa-ntn:ausf"
    required:
      - "base"

  - name: "nrf"
    fulltag: "shynuu/sa-ntn:nrf"
    required:
      - "base"

  - name: "pcf"
    fulltag: "shynuu/sa-ntn:pcf"
    required:
      - "base"

  - name: "udm"
    fulltag: "shynuu/sa-ntn:udm"
    required:
      - "base"

  - name: "udr"
    fulltag: "shynuu/sa-ntn:udr"
    required:
      - "base"

  - name: "upf"
    fulltag: "shynuu/sa-ntn:upf"
    required:
      - "base"

  - name: "qof"
    fulltag: "shynuu/sa-ntn:qof"
    required:
      - "base"

  - name: "ntnqof"
    fulltag: "shynuu/sa-ntn:ntnqof"
    required:
      - "base"

  - name: "nssf"
    fulltag: "shynuu/sa-ntn:nssf"
    required:
      - "base"

  - name: "trunks"
    fulltag: "shynuu/sa-ntn:trunks"
    required:

  - name: "populate"
    fulltag: "shynuu/sa-ntn:populate"
    required:

  - name: "classifier"
    fulltag: "shynuu/sa-ntn:classifier"
    required:

  - name: "application"
    fulltag: "shynuu/sa-ntn:application"
    required:

  - name: "gnb"
    fulltag: "shynuu/sa-ntn:gnb"
    required:
      - "cmake"
      - "ueransim"

  - name: "ue"
    fulltag: "shynuu/sa-ntn:ue"
    required:
      - "cmake"
      - "ueransim"

required:
  - name: "cmake"
    fulltag: "shynuu/sa-ntn:cmake"

  - name: "ueransim"
    fulltag: "shynuu/sa-ntn:ueransim"

  - name: "base"
    fulltag: "shynuu/sa-ntn:base"
